storyteller-api-message: StoryTellerAPI
random-image-ms-message: RandomImageMicroService
random-story-ms-message: RandomStoryMicroService
some: thing

logging:
# file: /var/memento/security.log
  level:
    com.codependent: 'INFO'
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
